#! /bin/sh
# /etc/init.d/usbcopy

### BEGIN INIT INFO
# Provides:          noip
# Required-Start:    dhcpd nfs-common
# Required-Stop:     dhcpd nfs-common
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Copy all Fotobox files to USB
# Description:       Copy all Fotobox files to USB
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting usbcopy"
    # run application you want to start
    python /home/pi/copyfiles.py > /home/pi/usbcopy.log
    ;;
  stop)
    echo "Stopping usbcopy"
    # kill application you want to stop
    # Add tasks
    ;;
  *)
    echo "Usage: /etc/init.d/usbcopy {start|stop}"
    exit 1
    ;;
esac

exit 0